In [202]:
import pandas as pd
dataset=pd.read_csv("Social_Network_Ads.csv")
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [203]:
dataset=pd.get_dummies(dataset, drop_first=True)
dataset=dataset.astype(int)
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [204]:
#dataset=dataset.drop("User ID",axis=1)
#If you want to drop any columns, use the above function.
#dataset

In [205]:
#to count the number of classes in my output. Here 1 is Purchased & 0 is not purchased
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [206]:
dataset.columns

Index(['User ID', 'Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [207]:
independent=dataset[['User ID', 'Age', 'EstimatedSalary', 'Gender_Male']]
dependent=dataset[["Purchased"]]

In [208]:
independent

      User ID  Age  EstimatedSalary  Gender_Male
0    15624510   19            19000            1
1    15810944   35            20000            1
2    15668575   26            43000            0
3    15603246   27            57000            0
4    15804002   19            76000            1
..        ...  ...              ...          ...
395  15691863   46            41000            0
396  15706071   51            23000            1
397  15654296   50            20000            0
398  15755018   36            33000            1
399  15594041   49            36000            0

[400 rows x 4 columns]

In [209]:
#if you want to view the Number of rows and columns in a tuple, use shape attribute from pandas
independent.shape

(400, 4)

In [210]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(independent, dependent, test_size=0.03, random_state=0)

In [211]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

C:\Anaconda3\Lib\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [212]:
y_pred = classifier.predict(X_test)

In [217]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[10  1]
 [ 0  1]]

In [214]:
from sklearn.metrics import classification_report
class_report = classification_report(y_test, y_pred)
print(class_report)

              precision    recall  f1-score   support

           0       1.00      0.91      0.95        11
           1       0.50      1.00      0.67         1

    accuracy                           0.92        12
   macro avg       0.75      0.95      0.81        12
weighted avg       0.96      0.92      0.93        12

In [216]:
result=classifier.predict([[15810944, 35, 20000, 1]])
result

C:\Anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array([0])