In [1]:
import pandas as pd
dataset = pd.read_csv("CKD.csv")
dataset = pd.get_dummies(dataset, drop_first=True, dtype=int)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [2]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [3]:
ind = dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dep = dataset[['classification_yes']]

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(ind, dep, test_size=0.3, random_state=0)

In [5]:
# from sklearn.preprocessing import StandardScaler
# scx = StandardScaler()
# X_train = scx.fit_transform(X_train)
# X_test = scx.transform(X_test)
# scy=StandardScaler()
# y_train = scy.fit_transform(y_train)
# y_test = scy.transform (y_test)

In [6]:
from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import KFold

param_grid = {'alpha' : [1.0, 2.0],
              'binarize' : [0.0, 1.0]}

grid = GridSearchCV(BernoulliNB(), param_grid, refit = True, verbose =3 , n_jobs=-1, cv=KFold(), scoring='f1_weighted')
grid.fit(X_train, y_train)

Fitting 5 folds for each of 4 candidates, totalling 20 fits

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=BernoulliNB(), n_jobs=-1,
             param_grid={'alpha': [1.0, 2.0], 'binarize': [0.0, 1.0]},
             scoring='f1_weighted', verbose=3)

In [7]:
re = grid.cv_results_
table = pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_alpha,param_binarize,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.025729,0.002472,0.009145,0.001677,1.0,0.0,"{'alpha': 1.0, 'binarize': 0.0}",0.896429,0.982195,0.876841,0.982160,0.981939,0.943913,0.047176,1
1,0.026069,0.003662,0.010065,0.000204,1.0,1.0,"{'alpha': 1.0, 'binarize': 1.0}",0.797704,0.778571,0.836407,0.836918,0.866491,0.823218,0.031236,3
2,0.015421,0.008788,0.009722,0.001537,2.0,0.0,"{'alpha': 2.0, 'binarize': 0.0}",0.896429,0.964472,0.876841,0.964331,0.981939,0.936802,0.041919,2
3,0.006360,0.001505,0.006489,0.002349,2.0,1.0,"{'alpha': 2.0, 'binarize': 1.0}",0.797704,0.778571,0.836407,0.836918,0.866491,0.823218,0.031236,3

In [8]:
table.to_excel("BernoulliNB_Class_Grid.xlsx")

In [9]:
grid_pred = grid.predict(X_test)

In [10]:
print("Evaluation metrics details for BernoulliNB are given below")
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_pred)
print("1) Confusion Matrix:\n",cm)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_pred)
print('2) classification report:\n', clf_report)
from sklearn.metrics import roc_auc_score
ras = roc_auc_score(y_test, grid.predict_proba(X_test)[:,1])
print("3) roc_auc_score is", ras)
print("4) The best parameters from GridSearchCV for the created BernoulliNB model are : \n" , grid.best_params_)

Evaluation metrics details for BernoulliNB are given below
1) Confusion Matrix:
 [[45  0]
 [ 8 67]]
2) classification report:
               precision    recall  f1-score   support

           0       0.85      1.00      0.92        45
           1       1.00      0.89      0.94        75

    accuracy                           0.93       120
   macro avg       0.92      0.95      0.93       120
weighted avg       0.94      0.93      0.93       120

3) roc_auc_score is 0.9967407407407407
4) The best parameters from GridSearchCV for the created BernoulliNB model are :
 {'alpha': 1.0, 'binarize': 0.0}

In [11]:
result = grid.predict([[2, 76.4599483204134, 3, 0, 148.112676056338, 57.4821052631579, 3.0773560209424, 137.52875399361, 4.62724358974359, 12.5181556195965, 38.8689024390243, 8408.19112627986, 4.70559701492537, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,1,1,0]])
result

C:\Anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but BernoulliNB was fitted with feature names
  warnings.warn(

array([1])

In [12]:
from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import ComplementNB
from sklearn.model_selection import KFold
param_grid = {'alpha' : [1.0, 0],
             'norm' : [True, False]}
grid = GridSearchCV(ComplementNB(), param_grid, refit = True, verbose =3 , n_jobs=-1, cv=KFold(), scoring='f1_weighted')
grid.fit(X_train, y_train)

Fitting 5 folds for each of 4 candidates, totalling 20 fits

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=ComplementNB(), n_jobs=-1,
             param_grid={'alpha': [1.0, 0], 'norm': [True, False]},
             scoring='f1_weighted', verbose=3)

In [13]:
re = grid.cv_results_
table1 = pd.DataFrame.from_dict(re)
table1

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_alpha,param_norm,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.008332,0.000859,0.017157,0.002418,1.0,True,"{'alpha': 1.0, 'norm': True}",0.141389,0.239150,0.204545,0.294425,0.161395,0.208181,0.054882,4
1,0.012085,0.001731,0.016800,0.001906,1.0,False,"{'alpha': 1.0, 'norm': False}",0.828591,0.840365,0.859375,0.874161,0.858518,0.852202,0.015945,1
2,0.017209,0.001429,0.017305,0.002413,0.0,True,"{'alpha': 0, 'norm': True}",0.571805,0.436998,0.480769,0.373754,0.541107,0.480887,0.071128,2
3,0.012599,0.002225,0.012509,0.002321,0.0,False,"{'alpha': 0, 'norm': False}",0.571805,0.436998,0.480769,0.373754,0.541107,0.480887,0.071128,2

In [14]:
table1.to_excel("ComplementNB_Class_Grid.xlsx")

In [15]:
grid_pred = grid.predict(X_test)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print("Evaluation metrics details for ComplementNB are given below")
cm = confusion_matrix(y_test, grid_pred)
print("1) Confusion Matrix:\n",cm)
clf_report = classification_report(y_test, grid_pred)
print('2) classification report:\n', clf_report)
from sklearn.metrics import roc_auc_score
ras = roc_auc_score(y_test, grid.predict_proba(X_test)[:,1])
print("3) roc_auc_score is", ras)
print("4) The best parameters from GridSearchCV for the created ComplementNB model are : \n" , grid.best_params_)

Evaluation metrics details for ComplementNB are given below
1) Confusion Matrix:
 [[44  1]
 [22 53]]
2) classification report:
               precision    recall  f1-score   support

           0       0.67      0.98      0.79        45
           1       0.98      0.71      0.82        75

    accuracy                           0.81       120
   macro avg       0.82      0.84      0.81       120
weighted avg       0.86      0.81      0.81       120

3) roc_auc_score is 0.9099259259259259
4) The best parameters from GridSearchCV for the created ComplementNB model are :
 {'alpha': 1.0, 'norm': False}

In [16]:
result = grid.predict([[2, 76.4599483204134, 3, 0, 148.112676056338, 57.4821052631579, 3.0773560209424, 137.52875399361, 4.62724358974359, 12.5181556195965, 38.8689024390243, 8408.19112627986, 4.70559701492537, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,1,1,0]])
result

C:\Anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but ComplementNB was fitted with feature names
  warnings.warn(

array([1])

In [17]:
from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import KFold
param_grid = {'var_smoothing': [1e-09, 1e-08, 1e-07, 1e-06, 1e-05]}
grid = GridSearchCV(GaussianNB(), param_grid, verbose =3 , n_jobs=-1, cv=KFold(), scoring='f1_weighted')
grid.fit(X_train, y_train)
grid_pred = grid.predict(X_test)

Fitting 5 folds for each of 5 candidates, totalling 25 fits

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [18]:
re = grid.cv_results_
table2 = pd.DataFrame.from_dict(re)
table2

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_var_smoothing,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.006575,0.001571,0.006994,0.001501,1.000000e-09,{'var_smoothing': 1e-09},0.982282,1.000000,0.964286,1.000000,0.981939,0.985701,0.013367,1
1,0.006232,0.001392,0.007782,0.001272,1.000000e-08,{'var_smoothing': 1e-08},0.913380,0.946793,0.964572,0.982160,0.981939,0.957769,0.025754,2
2,0.005368,0.000893,0.006734,0.000815,1.000000e-07,{'var_smoothing': 1e-07},0.845623,0.929124,0.841610,0.910572,0.946400,0.894666,0.043213,3
3,0.004822,0.000917,0.007585,0.001410,1.000000e-06,{'var_smoothing': 1e-06},0.845623,0.893681,0.805644,0.836961,0.858953,0.848173,0.028734,4
4,0.004682,0.001113,0.005788,0.002057,1.000000e-05,{'var_smoothing': 1e-05},0.794184,0.857873,0.805644,0.798672,0.823740,0.816023,0.023224,5

In [19]:
table2.to_excel("GaussianNB_Class_Grid.xlsx")

In [20]:
grid_pred = grid.predict(X_test)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print("Evaluation metrics details for GaussianNB are given below")
cm = confusion_matrix(y_test, grid_pred)
print("1) Confusion Matrix:\n",cm)
clf_report = classification_report(y_test, grid_pred)
print('2) classification report:\n', clf_report)
from sklearn.metrics import roc_auc_score
ras = roc_auc_score(y_test, grid.predict_proba(X_test)[:,1])
print("3) roc_auc_score is", ras)
print("4) The best parameters from GridSearchCV for the created GaussianNB model are : \n" , grid.best_params_)

Evaluation metrics details for GaussianNB are given below
1) Confusion Matrix:
 [[45  0]
 [ 2 73]]
2) classification report:
               precision    recall  f1-score   support

           0       0.96      1.00      0.98        45
           1       1.00      0.97      0.99        75

    accuracy                           0.98       120
   macro avg       0.98      0.99      0.98       120
weighted avg       0.98      0.98      0.98       120

3) roc_auc_score is 1.0
4) The best parameters from GridSearchCV for the created GaussianNB model are :
 {'var_smoothing': 1e-09}

In [21]:
result = grid.predict([[2, 76.4599483204134, 3, 0, 148.112676056338, 57.4821052631579, 3.0773560209424, 137.52875399361, 4.62724358974359, 12.5181556195965, 38.8689024390243, 8408.19112627986, 4.70559701492537, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,1,1,0]])
result

C:\Anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(

array([1])

In [22]:
from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import KFold
param_grid = {'alpha': [0.1, 0.5, 1.0, 2.0, 5.0]}
grid = GridSearchCV(MultinomialNB(), param_grid, verbose =3 , n_jobs=-1, cv=KFold(), scoring='f1_weighted')
grid.fit(X_train, y_train)
grid_pred = grid.predict(X_test)

Fitting 5 folds for each of 5 candidates, totalling 25 fits

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [23]:
re = grid.cv_results_
table3 = pd.DataFrame.from_dict(re)
table3

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_alpha,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.009936,0.002544,0.011888,0.002067,0.1,{'alpha': 0.1},0.862585,0.858242,0.894269,0.892447,0.893247,0.880158,0.016190,1
1,0.008554,0.000891,0.009045,0.000990,0.5,{'alpha': 0.5},0.828591,0.858242,0.859375,0.892447,0.875876,0.862906,0.021226,2
2,0.006470,0.000933,0.008969,0.001169,1.0,{'alpha': 1.0},0.828591,0.858242,0.859375,0.874161,0.858518,0.855777,0.014857,3
3,0.006398,0.001490,0.005357,0.000770,2.0,{'alpha': 2.0},0.811455,0.840365,0.841837,0.874161,0.858518,0.845267,0.020926,4
4,0.003558,0.002295,0.006219,0.002523,5.0,{'alpha': 5.0},0.811455,0.785714,0.841837,0.855678,0.858518,0.830640,0.027985,5

In [24]:
table3.to_excel("MultinomialNB_Class_Grid.xlsx")

In [25]:
grid_pred = grid.predict(X_test)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print("Evaluation metrics details for MultinomialNB are given below")
cm = confusion_matrix(y_test, grid_pred)
print("1) Confusion Matrix:\n",cm)
clf_report = classification_report(y_test, grid_pred)
print('2) classification report:\n', clf_report)
from sklearn.metrics import roc_auc_score
ras = roc_auc_score(y_test, grid.predict_proba(X_test)[:,1])
print("3) roc_auc_score is", ras)
print("4) The best parameters from GridSearchCV for the created MultinomialNB model are : \n" , grid.best_params_)

Evaluation metrics details for MultinomialNB are given below
1) Confusion Matrix:
 [[44  1]
 [20 55]]
2) classification report:
               precision    recall  f1-score   support

           0       0.69      0.98      0.81        45
           1       0.98      0.73      0.84        75

    accuracy                           0.82       120
   macro avg       0.83      0.86      0.82       120
weighted avg       0.87      0.82      0.83       120

3) roc_auc_score is 0.9315555555555557
4) The best parameters from GridSearchCV for the created MultinomialNB model are :
 {'alpha': 0.1}

In [26]:
result = grid.predict([[2, 76.4599483204134, 3, 0, 148.112676056338, 57.4821052631579, 3.0773560209424, 137.52875399361, 4.62724358974359, 12.5181556195965, 38.8689024390243, 8408.19112627986, 4.70559701492537, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,1,1,0]])
result

C:\Anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(

array([1])